-- 4일차 집합연산자
-- 1.1 합집합
-- 1.1.1 UNION(중복허용안함), UNION ALL(중복허용)
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_NAME, EMP_ID FROM EMPLOYEE
WHERE SALARY >= 2400000; 
--ORA-01790: expression must have same datatype as corresponding expression
--UNION 사용조건
-- 1. 컬럼의 갯수가 같아야함.
-- 2. 컬럼의 데이터타입이 각각 같아야 함.

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_NAME, TO_NUMBER(EMP_ID) FROM EMPLOYEE
WHERE SALARY >= 2400000; -- TO_NUMBER로 EMP_ID의 데이터타입을 SALARY의 데이터타입과 같게 만듬.

-- 1.2 교집합
-- 1.2.1 INTERSECT
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

-- 1.3 차집합
-- 1.3.1 MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;


